# Generated by Django 5.2.4 on 2025-09-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
