# Generated by Django 5.2.4 on 2025-09-24 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_product_category_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSerial',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_serials', to='api.productcategory')),
            ],
        ),
    ]
