# Generated by Django 5.2.4 on 2025-09-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_productserial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productserial',
            name='serial_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
