# Generated by Django 5.2.4 on 2025-09-24 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_productserial_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='productserial',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_serials', to='api.subtask'),
        ),
    ]
