# Generated by Django 5.2.4 on 2025-10-04 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_productserial_subtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialSubTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('OK', 'OK'), ('Not_OK', 'Not OK')], default='pending', max_length=10)),
                ('product_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_subtasks', to='api.productserial')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_statuses', to='api.subtask')),
            ],
            options={
                'unique_together': {('product_serial', 'subtask')},
            },
        ),
    ]
