# Generated by Django 5.2.4 on 2025-10-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_serialsubtaskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialsubtaskstatus',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serialsubtaskstatus',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
