# Generated by Django 5.2.4 on 2025-10-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_serialsubtaskstatus_update_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serialsubtaskstatus',
            name='updated_by',
        ),
    ]
