# Generated by Django 5.2.4 on 2025-10-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_serialsubtaskstatus_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialsubtaskstatus',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
