# Generated by Django 5.2.4 on 2025-10-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_serialsubtaskstatus_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialsubtaskstatus',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
